title: Scala Commons React Native

baseurl: "/scommons-react-native" # the subpath of your site, e.g. /blog

# Build settings
theme: jekyll-theme-cayman

#plugins:
#  - jekyll-feed
#  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
