name: CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Cache sbt
      uses: actions/cache@v2
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier/cache/v1
          ~/.cache/coursier/v1
        key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt', 'project/**/*.scala') }}

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ~/.nvm
          ~/work/scommons-react-native/scommons-react-native/showcase/node_modules
          ~/work/scommons-react-native/scommons-react-native/showcase/package-lock.json
          ~/work/scommons-react-native/scommons-react-native/showcase/target/scala-2.13/scalajs-bundler/main/node_modules
          ~/work/scommons-react-native/scommons-react-native/showcase/target/scala-2.13/scalajs-bundler/main/package-lock.json
          ~/work/scommons-react-native/scommons-react-native/showcase/target/scala-2.13/scalajs-bundler/test/node_modules
          ~/work/scommons-react-native/scommons-react-native/showcase/target/scala-2.13/scalajs-bundler/test/package-lock.json
          ~/work/scommons-react-native/scommons-react-native/core/target/scala-2.13/scalajs-bundler/test/node_modules
          ~/work/scommons-react-native/scommons-react-native/core/target/scala-2.13/scalajs-bundler/test/package-lock.json
          ~/work/scommons-react-native/scommons-react-native/community/target/scala-2.13/scalajs-bundler/test/node_modules
          ~/work/scommons-react-native/scommons-react-native/community/target/scala-2.13/scalajs-bundler/test/package-lock.json
          ~/work/scommons-react-native/scommons-react-native/expo/target/scala-2.13/scalajs-bundler/test/node_modules
          ~/work/scommons-react-native/scommons-react-native/expo/target/scala-2.13/scalajs-bundler/test/package-lock.json
          ~/work/scommons-react-native/scommons-react-native/navigation/target/scala-2.13/scalajs-bundler/test/node_modules
          ~/work/scommons-react-native/scommons-react-native/navigation/target/scala-2.13/scalajs-bundler/test/package-lock.json
          ~/work/scommons-react-native/scommons-react-native/test/target/scala-2.13/scalajs-bundler/test/node_modules
          ~/work/scommons-react-native/scommons-react-native/test/target/scala-2.13/scalajs-bundler/test/package-lock.json
          ~/work/scommons-react-native/scommons-react-native/ui/target/scala-2.13/scalajs-bundler/test/node_modules
          ~/work/scommons-react-native/scommons-react-native/ui/target/scala-2.13/scalajs-bundler/test/package-lock.json
        key: ${{ runner.os }}-node_modules-cache-v2-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-cache-v2-

    - name: Extract Tag Name
      run: echo "TAG_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      if: ${{ startsWith(github.ref, 'refs/tags') }}

    - name: Run tests
      run: |
        sbt -mem 2048 coverage test
        sbt coverageAggregate coveralls
      if: ${{ env.TAG_NAME == '' }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Publish SNAPSHOT
      run: |
        sbt clean publish
        echo "Publish to expo"
        sbt -mem 2048 "project scommons-react-native-showcase" fullOptJS
        cd showcase
        npm install
        npm install expo-cli@5 --save-dev
        ./node_modules/expo-cli/bin/expo.js login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        NODE_OPTIONS=--max_old_space_size=4096 EXPO_ENV=production ./node_modules/expo-cli/bin/expo.js publish --non-interactive
      if: ${{ !github.event.pull_request && env.TAG_NAME == '' }}
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
        EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}

    - name: Publish RELEASE
      run: |
        mkdir ./keys
        echo $PGP_PUBLIC | base64 --decode > ./keys/pubring.gpg
        echo $PGP_SECRET | base64 --decode > ./keys/secring.gpg
        VERSION="$(echo "$TAG_NAME" | cut -d'v' -f 2)"
        echo "Publish a release version=$VERSION for tag $TAG_NAME"
        version=$VERSION sbt clean publishSigned sonatypeBundleRelease
      if: ${{ env.TAG_NAME != '' }}
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        PGP_PUBLIC: ${{ secrets.PGP_PUBLIC }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        PGP_PASS: ${{ secrets.PGP_PASS }}
